spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        dialect: org.hibernate.dialect.MySQL8Dialect
#        cache:
#          use_second_level_cache: true
#          use_query_cache: true
#          use_structured_entries: true
#          region:
#            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
#      javax:
#        persistence.sharedCache.mode: ENABLE_SELECTIVE
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/ticket_booking
    username: root
    password: chandu95
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
    net:
      sf:
        ehcache=debug: